# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Write value to Properties-file
      uses: christian-draeger/write-properties@1.1.0
      with:
        path: './src/main/resources/application-prod.properties'
        property: |
          'spring.datasource.url'
          'spring.datasource.username'
          'spring.datasource.password'
          'truck.app-id'
          'truck.app-secret'
        value: |
          '${{ secrets.DB_URL }}'
          '${{ secrets.DB_USER }}'
          '${{ secrets.DB_PASSWORD }}'
          '${{ secrets.WX_APP_ID }}'
          '${{ secrets.WX_APP_SECRET }}'
      
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true
        
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.APP_SERVER }}
        username: root
        password: ${{ secrets.APP_SECRET }}
        source: "./target/truck-billing-0.0.1.jar"
        target: "/root/truck-java"
        strip_components: 1
        
    - name: ssh pipelines
      uses: cross-the-world/ssh-pipeline@master
      env:
        WELCOME: "ssh pipeline"
      with:
        host: ${{ secrets.APP_SERVER }}
        user: root
        pass: ${{ secrets.APP_SECRET }}
        port: 22
        connect_timeout: 10s
        script: |
          ps -ef | grep truck-billing-0.0.1.jar | grep -v grep | awk '{print $2}' | xargs kill -9
          cd /root/truck-java
          nohup java -jar -Dspring.profiles.active=prod truck-billing-0.0.1.jar > run.log &
          
    

